require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VolunteerApplicationsController do

  # This should return the minimal set of attributes required to create a valid
  # VolunteerApplication. As you add validations to VolunteerApplication, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VolunteerApplicationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all volunteer_applications as @volunteer_applications" do
      volunteer_application = VolunteerApplication.create! valid_attributes
      get :index, {}, valid_session
      assigns(:volunteer_applications).should eq([volunteer_application])
    end
  end

  describe "GET show" do
    it "assigns the requested volunteer_application as @volunteer_application" do
      volunteer_application = VolunteerApplication.create! valid_attributes
      get :show, {:id => volunteer_application.to_param}, valid_session
      assigns(:volunteer_application).should eq(volunteer_application)
    end
  end

  describe "GET new" do
    it "assigns a new volunteer_application as @volunteer_application" do
      get :new, {}, valid_session
      assigns(:volunteer_application).should be_a_new(VolunteerApplication)
    end
  end

  describe "GET edit" do
    it "assigns the requested volunteer_application as @volunteer_application" do
      volunteer_application = VolunteerApplication.create! valid_attributes
      get :edit, {:id => volunteer_application.to_param}, valid_session
      assigns(:volunteer_application).should eq(volunteer_application)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new VolunteerApplication" do
        expect {
          post :create, {:volunteer_application => valid_attributes}, valid_session
        }.to change(VolunteerApplication, :count).by(1)
      end

      it "assigns a newly created volunteer_application as @volunteer_application" do
        post :create, {:volunteer_application => valid_attributes}, valid_session
        assigns(:volunteer_application).should be_a(VolunteerApplication)
        assigns(:volunteer_application).should be_persisted
      end

      it "redirects to the created volunteer_application" do
        post :create, {:volunteer_application => valid_attributes}, valid_session
        response.should redirect_to(VolunteerApplication.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved volunteer_application as @volunteer_application" do
        # Trigger the behavior that occurs when invalid params are submitted
        VolunteerApplication.any_instance.stub(:save).and_return(false)
        post :create, {:volunteer_application => {  }}, valid_session
        assigns(:volunteer_application).should be_a_new(VolunteerApplication)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        VolunteerApplication.any_instance.stub(:save).and_return(false)
        post :create, {:volunteer_application => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested volunteer_application" do
        volunteer_application = VolunteerApplication.create! valid_attributes
        # Assuming there are no other volunteer_applications in the database, this
        # specifies that the VolunteerApplication created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        VolunteerApplication.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => volunteer_application.to_param, :volunteer_application => { "these" => "params" }}, valid_session
      end

      it "assigns the requested volunteer_application as @volunteer_application" do
        volunteer_application = VolunteerApplication.create! valid_attributes
        put :update, {:id => volunteer_application.to_param, :volunteer_application => valid_attributes}, valid_session
        assigns(:volunteer_application).should eq(volunteer_application)
      end

      it "redirects to the volunteer_application" do
        volunteer_application = VolunteerApplication.create! valid_attributes
        put :update, {:id => volunteer_application.to_param, :volunteer_application => valid_attributes}, valid_session
        response.should redirect_to(volunteer_application)
      end
    end

    describe "with invalid params" do
      it "assigns the volunteer_application as @volunteer_application" do
        volunteer_application = VolunteerApplication.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VolunteerApplication.any_instance.stub(:save).and_return(false)
        put :update, {:id => volunteer_application.to_param, :volunteer_application => {  }}, valid_session
        assigns(:volunteer_application).should eq(volunteer_application)
      end

      it "re-renders the 'edit' template" do
        volunteer_application = VolunteerApplication.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VolunteerApplication.any_instance.stub(:save).and_return(false)
        put :update, {:id => volunteer_application.to_param, :volunteer_application => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested volunteer_application" do
      volunteer_application = VolunteerApplication.create! valid_attributes
      expect {
        delete :destroy, {:id => volunteer_application.to_param}, valid_session
      }.to change(VolunteerApplication, :count).by(-1)
    end

    it "redirects to the volunteer_applications list" do
      volunteer_application = VolunteerApplication.create! valid_attributes
      delete :destroy, {:id => volunteer_application.to_param}, valid_session
      response.should redirect_to(volunteer_applications_url)
    end
  end

end
